name: Docker Build
on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  lookup-versions:
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Get current versions
        id: versions
        run: |
          echo "versions=$(python -c 'import glob, json; print(json.dumps(glob.glob("1.*")))')" | tee $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    needs:
      - lookup-versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.lookup-versions.outputs.versions) }}
        type: [apache, fpm, fpm-alpine]

    steps:
      - uses: actions/checkout@v4
      - run: docker build ./${{ matrix.version }}/${{ matrix.type }}
